# This config is for the frontend container I create. I need to change the default nginx to support SPA routing
server {
    listen 80;
    listen [::]:80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}