FROM node:20-alpine AS build
EXPOSE 4200

# Set working directory
WORKDIR /Crafty

# Install Angular CLI globally
RUN npm install -g @angular/cli@^18

# Copy repository and install
RUN apk add --no-cache git \
    && git clone --recurse-submodules https://codeberg.org/Prime8bit/Crafty.git . 

# Expose Angular dev server port

WORKDIR /Crafty/client

RUN npm install

# Start Angular app in dev mode
CMD ["ng", "serve", "--host", "0.0.0.0"]