services:
  crafty-nginx:
    container_name: crafty-nginx
    image: nginx:1.31.3
    profiles: ["production"]
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - crafty-backend
      - crafty-frontend
      

  crafty-frontend:
    container_name: crafty-frontend
    image: crafty-frontend:latest
    profiles: ["production"]
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:80" # dev versions of angular run on 4200 by default. Since 80 is already in use by nginx anyway, I may as well follow suit
    restart: unless-stopped
    depends_on:
      - crafty-backend
  
  crafty-backend:
    container_name: crafty-backend
    image: crafty-backend:latest
    profiles: ["production"]
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_TOKEN_KEY: ${JWT_TOKEN_KEY}

      CloudinarySettings__CloudName: ${CloudinarySettings__CloudName}
      CloudinarySettings__ApiKey: ${CloudinarySettings__ApiKey}
      CloudinarySettings__ApiSecret: ${CloudinarySettings__ApiSecret}
    depends_on:
      - crafty-db
      - crafty-redis
  
  crafty-db:
    container_name: crafty-db
    image: postgres:18
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      # uncomment this if you want a persistent database, for this portfolio piece. I want the database to reset on each boot.
      # - ./dbData:/var/lib/postgresql/data
      - ./API/DbBackup.sql:/docker-entrypoint-initdb.d/init.sql:ro

  crafty-redis:
    container_name: crafty-redis
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]