limit_req_zone $binary_remote_addr zone=ipLimiterApi:10m rate=1r/s; # Remember the 10m refers to number of megabytes to denote for storing limiter data
limit_req_zone $binary_remote_addr zone=ipLimiterChat:10m rate=2r/s;
limit_req_status 429;

server {
    listen 80;
    listen [::]:80;

    server_name _;

    access_log /var/log/nginx/prime8bit-access.log;
    error_log  /var/log/nginx/prime8bit-error.log;

    client_max_body_size 10G;
    proxy_request_buffering off;
    proxy_buffering off;

    location / {
        proxy_pass http://crafty-frontend:80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://crafty-backend:5000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Burst=10 means it will allow 10 additional requests per period, but it rate limits them by period. I.e. if you allow 1r/s then it will allow 10 at a rate of 1r/s before returning an error.
        # nodely=5 means the first 10-5 ALLOWED additional requests by burst will be returned immediately, every request after that will be rate limited OR return an error
        limit_req zone=ipLimiterApi burst=30 delay=20; 
    }

    location /hubs/ {
        proxy_pass http://crafty-backend:5000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        limit_req zone=ipLimiterChat burst=150 delay=50; 
    }
}

# Gitea
server {
    listen 80;
    listen [::]:80;

    server_name dev.prime8bit.com;

    client_max_body_size 10G;
    proxy_request_buffering off;
    proxy_buffering off;
}
