apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretName }}
  labels:
    app: {{ .Values.db.app }}
type: Opaque
stringData:
  POSTGRES_DB: "crafty"
  POSTGRES_USER: "prime8bit"
  POSTGRES_PASSWORD: "password"