--
-- PostgreSQL database dump
--

\restrict PPbQ4RYiIbXzHLk3tLDlfuGiwnQJz2KoKkNgIktD1ebbG6BSzDU7MsgGvHiZVT9

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4 (Debian 18.4-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" bigint NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO prime8bit;

--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: prime8bit
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."AspNetRoles" (
    "Id" bigint NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO prime8bit;

--
-- Name: AspNetRoles_Id_seq; Type: SEQUENCE; Schema: public; Owner: prime8bit
--

ALTER TABLE public."AspNetRoles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" bigint NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO prime8bit;

--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: prime8bit
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" bigint NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO prime8bit;

--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" bigint NOT NULL,
    "RoleId" bigint NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO prime8bit;

--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" bigint NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO prime8bit;

--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."AspNetUsers" (
    "Id" bigint NOT NULL,
    "FullName" text NOT NULL,
    "DisplayName" text NOT NULL,
    "Address" text NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "LastActive" timestamp with time zone NOT NULL,
    "ProfileImageId" bigint NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO prime8bit;

--
-- Name: AspNetUsers_Id_seq; Type: SEQUENCE; Schema: public; Owner: prime8bit
--

ALTER TABLE public."AspNetUsers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUsers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CraftMedia; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."CraftMedia" (
    "Id" bigint NOT NULL,
    "CraftId" bigint NOT NULL,
    "Url" text NOT NULL,
    "CloudId" text,
    "Type" integer NOT NULL
);


ALTER TABLE public."CraftMedia" OWNER TO prime8bit;

--
-- Name: CraftMedia_Id_seq; Type: SEQUENCE; Schema: public; Owner: prime8bit
--

ALTER TABLE public."CraftMedia" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CraftMedia_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CraftWishlistItems; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."CraftWishlistItems" (
    "WishlistingUserId" bigint NOT NULL,
    "WishlistedCraftId" bigint NOT NULL
);


ALTER TABLE public."CraftWishlistItems" OWNER TO prime8bit;

--
-- Name: Crafts; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."Crafts" (
    "Id" bigint NOT NULL,
    "Name" text NOT NULL,
    "Price" real NOT NULL,
    "Description" text,
    "Stock" bigint NOT NULL,
    "CreatedAt" date NOT NULL,
    "IsArchived" boolean NOT NULL,
    "IsInappropriate" boolean NOT NULL,
    "SellerId" bigint NOT NULL,
    "SearchImageId" bigint
);


ALTER TABLE public."Crafts" OWNER TO prime8bit;

--
-- Name: Crafts_Id_seq; Type: SEQUENCE; Schema: public; Owner: prime8bit
--

ALTER TABLE public."Crafts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Crafts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MessageConnections; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."MessageConnections" (
    "Id" text NOT NULL,
    "MessageGroupName" text NOT NULL,
    "UserId" bigint NOT NULL
);


ALTER TABLE public."MessageConnections" OWNER TO prime8bit;

--
-- Name: MessageGroups; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."MessageGroups" (
    "Name" text NOT NULL
);


ALTER TABLE public."MessageGroups" OWNER TO prime8bit;

--
-- Name: Messages; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."Messages" (
    "Id" bigint NOT NULL,
    "Content" text NOT NULL,
    "DateRead" timestamp with time zone,
    "DateSent" timestamp with time zone NOT NULL,
    "SenderDeleted" boolean NOT NULL,
    "RecipientDeleted" boolean NOT NULL,
    "SenderId" bigint NOT NULL,
    "RecipientId" bigint NOT NULL
);


ALTER TABLE public."Messages" OWNER TO prime8bit;

--
-- Name: Messages_Id_seq; Type: SEQUENCE; Schema: public; Owner: prime8bit
--

ALTER TABLE public."Messages" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Messages_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: OrderItem; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."OrderItem" (
    "Id" bigint NOT NULL,
    "Quantity" integer NOT NULL,
    "PricePerCraft" real NOT NULL,
    "Discount" real NOT NULL,
    "Status" integer NOT NULL,
    "OrderId" bigint NOT NULL,
    "CraftId" bigint NOT NULL,
    "SellerId" bigint NOT NULL
);


ALTER TABLE public."OrderItem" OWNER TO prime8bit;

--
-- Name: OrderItem_Id_seq; Type: SEQUENCE; Schema: public; Owner: prime8bit
--

ALTER TABLE public."OrderItem" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrderItem_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Orders; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."Orders" (
    "Id" bigint NOT NULL,
    "OrderDate" date NOT NULL,
    "TotalPrice" real NOT NULL,
    "ShippingName" text NOT NULL,
    "ShippingAddress" text NOT NULL,
    "BillingName" text NOT NULL,
    "BillingAddress" text NOT NULL,
    "Status" integer NOT NULL,
    "BuyerId" bigint NOT NULL
);


ALTER TABLE public."Orders" OWNER TO prime8bit;

--
-- Name: Orders_Id_seq; Type: SEQUENCE; Schema: public; Owner: prime8bit
--

ALTER TABLE public."Orders" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Orders_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: UserMedia; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."UserMedia" (
    "Id" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "Url" text NOT NULL,
    "CloudId" text,
    "Type" integer NOT NULL
);


ALTER TABLE public."UserMedia" OWNER TO prime8bit;

--
-- Name: UserMedia_Id_seq; Type: SEQUENCE; Schema: public; Owner: prime8bit
--

ALTER TABLE public."UserMedia" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserMedia_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: prime8bit
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO prime8bit;

--
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: prime8bit
--



--
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: prime8bit
--

INSERT INTO public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (1, 'User', 'USER', NULL);
INSERT INTO public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") VALUES (2, 'Admin', 'ADMIN', NULL);


--
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: prime8bit
--



--
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: prime8bit
--



--
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: prime8bit
--

INSERT INTO public."AspNetUserRoles" ("UserId", "RoleId") VALUES (1, 1);
INSERT INTO public."AspNetUserRoles" ("UserId", "RoleId") VALUES (2, 1);
INSERT INTO public."AspNetUserRoles" ("UserId", "RoleId") VALUES (3, 1);
INSERT INTO public."AspNetUserRoles" ("UserId", "RoleId") VALUES (4, 1);
INSERT INTO public."AspNetUserRoles" ("UserId", "RoleId") VALUES (5, 1);
INSERT INTO public."AspNetUserRoles" ("UserId", "RoleId") VALUES (8, 1);


--
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: prime8bit
--



--
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: prime8bit
--

INSERT INTO public."AspNetUsers" ("Id", "FullName", "DisplayName", "Address", "Created", "LastActive", "ProfileImageId", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES (1, 'Lisa Scott', 'Lisa Scott', '9834 Brook Lane Nottingham, MD 21236', '2026-07-06 22:10:46.401343+00', '2026-07-06 22:10:46.401343+00', 0, 'zamora', 'ZAMORA', 'zamora@zensor.com', 'ZAMORA@ZENSOR.COM', false, 'AQAAAAIAAYagAAAAEDZDzAc14fBJUoG86C/ZYlSkgqplBS8lBzwSX+nnQ/pAAA8H6k++HTQeKw4912V+Lg==', 'BYAPHOAPRFRWHEE6JJAHYQDRAYLVOBVQ', '76a8f830-37bc-4344-863b-2b7bd4b7666f', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" ("Id", "FullName", "DisplayName", "Address", "Created", "LastActive", "ProfileImageId", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES (3, 'Frasier Crane', 'Frasier Crane', '736 Jackson Avenue Hendersonville, NC 28792', '2026-07-06 22:12:35.780516+00', '2026-07-06 22:12:35.780516+00', 0, 'cooper', 'COOPER', 'frasiercrane@bogus.com', 'FRASIERCRANE@BOGUS.COM', false, 'AQAAAAIAAYagAAAAEEe2cEYFXZxgtz1xjKR61g/SrhDOoDAZRnGbnM2s/Rj4U3sTLrbpes27AoByyplVeQ==', 'RLUMXRY2MCKJ6XZTWMQB3TON27KPVY6Y', '52e85e8b-fb19-4e27-952a-35809f5ab2e3', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" ("Id", "FullName", "DisplayName", "Address", "Created", "LastActive", "ProfileImageId", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES (4, 'Niles Crane', 'Niles Crane', '276 Cottage Street Monsey, NY 10952', '2026-07-06 22:13:11.64072+00', '2026-07-06 22:13:11.64072+00', 0, 'stanley', 'STANLEY', 'nilescrane@bogus.com', 'NILESCRANE@BOGUS.COM', false, 'AQAAAAIAAYagAAAAELKwxBaa9DVhP5NzaJgDbHoYQfyV2AQ0Avi/5eNjqNWuM6DA8HWc88Ur9zL0+EfOJA==', 'IVBVSX3DPSYZMGVGAYSPRO2E6Q5SDL2O', 'f9079a31-461c-4431-b5b4-9762e1e930db', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" ("Id", "FullName", "DisplayName", "Address", "Created", "LastActive", "ProfileImageId", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES (5, 'Gilbert Saunders', 'Gilbert Saunders', '37 8th Avenue Michigan City, IN 46360', '2026-07-06 22:13:40.551633+00', '2026-07-06 22:13:40.551633+00', 0, 'roach', 'ROACH', 'gilbertsaunders@bogus.com', 'GILBERTSAUNDERS@BOGUS.COM', false, 'AQAAAAIAAYagAAAAENioITZBU1kHmxnBOi9jua7sjVgfitE2hbMIFi9GwnyQwWOli0QDeZumMDoa84WGTw==', 'KITE5ZNQTKVXWGM4LLLIECRF5IVVF3T5', '259049f0-65f6-414a-8fb3-c41fd6580806', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" ("Id", "FullName", "DisplayName", "Address", "Created", "LastActive", "ProfileImageId", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES (8, 'Nate Thompson', 'Nate Thompson', '61 Evergreen Lane Harvey, IL 60426', '2026-07-06 22:15:13.459153+00', '2026-07-06 22:15:13.459153+00', 0, 'nate', 'NATE', 'nate@prime8bit.com', 'NATE@PRIME8BIT.COM', false, 'AQAAAAIAAYagAAAAEJK9RUD56V7WXiBsUVm9JtJj3/PVdhkRsGdgiImCxB4TZi6dHW9ho3ALbZIrt6Qwxw==', '5XZSURQYBVKDKL4PAN7YGVA6UYRQYSIQ', 'c4f7ce51-efd7-45e3-9086-959428c48496', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" ("Id", "FullName", "DisplayName", "Address", "Created", "LastActive", "ProfileImageId", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") VALUES (2, 'Roslyn Doyle', 'Roz', '29 Cardinal Drive Amarillo, TX 79106', '2026-07-06 22:11:57.693221+00', '2026-07-06 22:11:57.693221+00', 0, 'roslyn', 'ROSLYN', 'roslyndoyle@bogus.com', 'ROSLYNDOYLE@BOGUS.COM', false, 'AQAAAAIAAYagAAAAEEeGYb5OFNBst0sKUSAFZWs6HmJy8EqswauGXl51G3zRyFug0Yy0/o4bvTW9jvN2Sg==', 'IL5WQTJVGSRMGP2L35IXJSLD3TPIKILI', 'fdb25bc1-ec24-4c24-b3df-9af33218927a', NULL, false, false, NULL, true, 0);


--
-- Data for Name: Crafts; Type: TABLE DATA; Schema: public; Owner: prime8bit
--

INSERT INTO public."Crafts" ("Id", "Name", "Price", "Description", "Stock", "CreatedAt", "IsArchived", "IsInappropriate", "SellerId", "SearchImageId") VALUES (15, 'Chinchilla', 43.23, 'Chinchilla is cool', 1, '2025-08-19', false, false, 1, NULL);
INSERT INTO public."Crafts" ("Id", "Name", "Price", "Description", "Stock", "CreatedAt", "IsArchived", "IsInappropriate", "SellerId", "SearchImageId") VALUES (39, 'Robot Arm', 52, 'This is a cool robot arm.', 6, '2025-08-19', false, false, 1, NULL);
INSERT INTO public."Crafts" ("Id", "Name", "Price", "Description", "Stock", "CreatedAt", "IsArchived", "IsInappropriate", "SellerId", "SearchImageId") VALUES (1, 'Squirrel', 12.34, 'Crafty Squirrel', 0, '2021-06-29', true, false, 1, NULL);
INSERT INTO public."Crafts" ("Id", "Name", "Price", "Description", "Stock", "CreatedAt", "IsArchived", "IsInappropriate", "SellerId", "SearchImageId") VALUES (19, 'Powder', 124, 'Powder is a good pupper.', 5, '2025-08-19', false, false, 1, NULL);
INSERT INTO public."Crafts" ("Id", "Name", "Price", "Description", "Stock", "CreatedAt", "IsArchived", "IsInappropriate", "SellerId", "SearchImageId") VALUES (26, 'Bird', 25.13, 'It has reddish orange feathers near its head and looks cute on a fishing pole.', 7, '2025-08-19', false, false, 8, NULL);
INSERT INTO public."Crafts" ("Id", "Name", "Price", "Description", "Stock", "CreatedAt", "IsArchived", "IsInappropriate", "SellerId", "SearchImageId") VALUES (27, 'Bunny', 60.33, 'Baby bunny.', 9, '2025-08-19', false, false, 8, NULL);
INSERT INTO public."Crafts" ("Id", "Name", "Price", "Description", "Stock", "CreatedAt", "IsArchived", "IsInappropriate", "SellerId", "SearchImageId") VALUES (28, 'Frog Cat', 56.12, 'This cat looks adorable on its frog pillow.', 15, '2025-08-19', false, false, 8, NULL);
INSERT INTO public."Crafts" ("Id", "Name", "Price", "Description", "Stock", "CreatedAt", "IsArchived", "IsInappropriate", "SellerId", "SearchImageId") VALUES (29, 'Corgi', 68.84, 'Cute corgi puppy.', 43, '2025-08-19', false, false, 2, NULL);
INSERT INTO public."Crafts" ("Id", "Name", "Price", "Description", "Stock", "CreatedAt", "IsArchived", "IsInappropriate", "SellerId", "SearchImageId") VALUES (30, 'Cow', 73.21, 'Baby cow in the back of a car.', 34, '2025-08-19', false, false, 2, NULL);
INSERT INTO public."Crafts" ("Id", "Name", "Price", "Description", "Stock", "CreatedAt", "IsArchived", "IsInappropriate", "SellerId", "SearchImageId") VALUES (31, 'Dog and Kitten', 11.11, 'A black dog that cares for a black cat.', 2, '2025-08-19', false, false, 2, NULL);
INSERT INTO public."Crafts" ("Id", "Name", "Price", "Description", "Stock", "CreatedAt", "IsArchived", "IsInappropriate", "SellerId", "SearchImageId") VALUES (32, 'Fox', 39.23, 'The quick brown fox jumped over the lazy dog. I mean it is technically reddish orange, but you get it.', 3, '2025-08-19', false, false, 3, NULL);
INSERT INTO public."Crafts" ("Id", "Name", "Price", "Description", "Stock", "CreatedAt", "IsArchived", "IsInappropriate", "SellerId", "SearchImageId") VALUES (33, 'Mouse', 22.22, 'A mouse in the hand is worth two in the bush.', 3, '2025-08-19', false, false, 3, NULL);
INSERT INTO public."Crafts" ("Id", "Name", "Price", "Description", "Stock", "CreatedAt", "IsArchived", "IsInappropriate", "SellerId", "SearchImageId") VALUES (34, 'Stoat', 33.33, 'What is the difference between a stoat and a weasel anyway?', 4, '2025-08-19', false, false, 3, NULL);
INSERT INTO public."Crafts" ("Id", "Name", "Price", "Description", "Stock", "CreatedAt", "IsArchived", "IsInappropriate", "SellerId", "SearchImageId") VALUES (35, 'Walleye', 44.44, 'I like fish', 45, '2025-08-19', false, false, 4, NULL);
INSERT INTO public."Crafts" ("Id", "Name", "Price", "Description", "Stock", "CreatedAt", "IsArchived", "IsInappropriate", "SellerId", "SearchImageId") VALUES (38, 'Frog', 5, 'Tree Frog', 3, '2025-08-19', false, false, 1, NULL);

--
-- Data for Name: CraftMedia; Type: TABLE DATA; Schema: public; Owner: prime8bit
--

INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (57, 1, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770339220/Crafty/vgtbueoiaz9epfdpufh6.jpg', 'Crafty/vgtbueoiaz9epfdpufh6', 1);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (51, 15, 'https://res.cloudinary.com/db3ulheek/video/upload/v1773889468/Crafty/adbcbovy9cizhui4mdvy.mp4', 'Crafty/adbcbovy9cizhui4mdvy', 2);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (73, 15, 'https://res.cloudinary.com/db3ulheek/image/upload/v1744514246/Crafty/uzvrmsypkklrrv9qjx86.jpg', 'Crafty/uzvrmsypkklrrv9qjx86', 1);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (37, 19, 'https://res.cloudinary.com/db3ulheek/image/upload/v1754206616/Crafty/mqhuqin26kpmaiqunylu.jpg', 'Crafty/mqhuqin26kpmaiqunylu', 1);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (60, 26, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770773032/Crafty/ihjj2pihzovifnvt4iv1.webp', 'Crafty/ihjj2pihzovifnvt4iv1', 1);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (61, 27, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770773090/Crafty/zd4vitbbmvhxoizwbrpc.webp', 'Crafty/zd4vitbbmvhxoizwbrpc', 1);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (62, 28, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770773141/Crafty/yzu8cm82umilihqnrggu.webp', 'Crafty/yzu8cm82umilihqnrggu', 1);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (63, 29, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770773539/Crafty/pcnguuzwefayjc3z8gxt.webp', 'Crafty/pcnguuzwefayjc3z8gxt', 1);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (64, 30, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770773573/Crafty/mt0r1allohsmbk2k8rvz.webp', 'Crafty/mt0r1allohsmbk2k8rvz', 1);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (65, 31, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770773620/Crafty/kpq0prjlrzzkutyuy0yr.webp', 'Crafty/kpq0prjlrzzkutyuy0yr', 1);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (66, 32, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770773722/Crafty/kt2ac1qynaoeokpfcikh.webp', 'Crafty/kt2ac1qynaoeokpfcikh', 1);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (67, 33, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770773762/Crafty/rfwlhad00kgdppoiojsg.webp', 'Crafty/rfwlhad00kgdppoiojsg', 1);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (68, 34, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770773811/Crafty/aqxemtcdjzjsedch1odd.webp', 'Crafty/aqxemtcdjzjsedch1odd', 1);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (69, 35, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770773887/Crafty/ssq1bnxzmif7unefjzkt.png', 'Crafty/ssq1bnxzmif7unefjzkt', 1);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (72, 38, 'https://res.cloudinary.com/db3ulheek/image/upload/v1771043789/Crafty/b9tim7jihwejror8v5yi.jpg', 'Crafty/b9tim7jihwejror8v5yi', 1);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (74, 39, 'https://res.cloudinary.com/db3ulheek/raw/upload/v1773891581/Crafty/t1gzzb8ynk7tperoefh4.glb', 'Crafty/t1gzzb8ynk7tperoefh4.glb', 3);
INSERT INTO public."CraftMedia" ("Id", "CraftId", "Url", "CloudId", "Type") VALUES (75, 39, 'https://res.cloudinary.com/db3ulheek/image/upload/v1773891518/Crafty/iyaozxh43pawlastr2xs.jpg', 'Crafty/iyaozxh43pawlastr2xs', 1);


-- Updating Crafts with profile image id's now that CraftMedia exist
UPDATE public."Crafts" SET "SearchImageId" = 73 WHERE "Id" = 15;
UPDATE public."Crafts" SET "SearchImageId" = 75 WHERE "Id" = 39;
UPDATE public."Crafts" SET "SearchImageId" = 57 WHERE "Id" = 1;
UPDATE public."Crafts" SET "SearchImageId" = 37 WHERE "Id" = 19;
UPDATE public."Crafts" SET "SearchImageId" = 60 WHERE "Id" = 26;
UPDATE public."Crafts" SET "SearchImageId" = 61 WHERE "Id" = 27;
UPDATE public."Crafts" SET "SearchImageId" = 62 WHERE "Id" = 28;
UPDATE public."Crafts" SET "SearchImageId" = 63 WHERE "Id" = 29;
UPDATE public."Crafts" SET "SearchImageId" = 64 WHERE "Id" = 30;
UPDATE public."Crafts" SET "SearchImageId" = 65 WHERE "Id" = 31;
UPDATE public."Crafts" SET "SearchImageId" = 66 WHERE "Id" = 32;
UPDATE public."Crafts" SET "SearchImageId" = 67 WHERE "Id" = 33;
UPDATE public."Crafts" SET "SearchImageId" = 68 WHERE "Id" = 34;
UPDATE public."Crafts" SET "SearchImageId" = 69 WHERE "Id" = 35;
UPDATE public."Crafts" SET "SearchImageId" = 72 WHERE "Id" = 38;

--
-- Data for Name: CraftWishlistItems; Type: TABLE DATA; Schema: public; Owner: prime8bit
--

INSERT INTO public."CraftWishlistItems" ("WishlistingUserId", "WishlistedCraftId") VALUES (1, 31);
INSERT INTO public."CraftWishlistItems" ("WishlistingUserId", "WishlistedCraftId") VALUES (1, 32);
INSERT INTO public."CraftWishlistItems" ("WishlistingUserId", "WishlistedCraftId") VALUES (1, 28);



--
-- Data for Name: MessageConnections; Type: TABLE DATA; Schema: public; Owner: prime8bit
--



--
-- Data for Name: MessageGroups; Type: TABLE DATA; Schema: public; Owner: prime8bit
--



--
-- Data for Name: Messages; Type: TABLE DATA; Schema: public; Owner: prime8bit
--

INSERT INTO public."Messages" ("Id", "Content", "DateRead", "DateSent", "SenderDeleted", "RecipientDeleted", "SenderId", "RecipientId") VALUES (1, 'OMG! Powder is the cutest puppy. How old is she?', '2026-07-06 23:18:40.043022+00', '2026-07-06 23:18:33.307044+00', false, false, 2, 1);
INSERT INTO public."Messages" ("Id", "Content", "DateRead", "DateSent", "SenderDeleted", "RecipientDeleted", "SenderId", "RecipientId") VALUES (2, 'She is 3 years old. She barks like a banshee when the doorbell rings, but I still think she is pretty cute :3', '2026-07-06 23:19:37.419085+00', '2026-07-06 23:19:37.419085+00', false, false, 1, 2);
INSERT INTO public."Messages" ("Id", "Content", "DateRead", "DateSent", "SenderDeleted", "RecipientDeleted", "SenderId", "RecipientId") VALUES (4, 'I know right? It was a gift from my uncle.', '2026-07-06 23:20:39.520043+00', '2026-07-06 23:20:39.520043+00', false, false, 1, 2);
INSERT INTO public."Messages" ("Id", "Content", "DateRead", "DateSent", "SenderDeleted", "RecipientDeleted", "SenderId", "RecipientId") VALUES (3, 'I just saw your profile picture. That mustache is hilarious.', '2026-07-06 23:20:56.153243+00', '2026-07-06 23:20:23.533762+00', false, false, 2, 1);
INSERT INTO public."Messages" ("Id", "Content", "DateRead", "DateSent", "SenderDeleted", "RecipientDeleted", "SenderId", "RecipientId") VALUES (5, 'I love bunnies. Where did you find that?', NULL, '2026-07-06 23:23:12.329927+00', false, false, 1, 8);
INSERT INTO public."Messages" ("Id", "Content", "DateRead", "DateSent", "SenderDeleted", "RecipientDeleted", "SenderId", "RecipientId") VALUES (6, 'The mystical land of bunnies. Of course.', NULL, '2026-07-07 02:08:46.300261+00', false, false, 1, 8);
INSERT INTO public."Messages" ("Id", "Content", "DateRead", "DateSent", "SenderDeleted", "RecipientDeleted", "SenderId", "RecipientId") VALUES (7, 'Wouldn''t you say it makes me look dignified?', '2026-07-07 02:33:57.85524+00', '2026-07-07 02:33:29.935564+00', false, false, 1, 2);
INSERT INTO public."Messages" ("Id", "Content", "DateRead", "DateSent", "SenderDeleted", "RecipientDeleted", "SenderId", "RecipientId") VALUES (8, 'Not the word I would use ;P', '2026-07-07 02:34:25.17708+00', '2026-07-07 02:34:25.177079+00', false, false, 2, 1);


--
-- Data for Name: OrderItem; Type: TABLE DATA; Schema: public; Owner: prime8bit
--

INSERT INTO public."OrderItem" ("Id", "Quantity", "PricePerCraft", "Discount", "Status", "OrderId", "CraftId", "SellerId") VALUES (1, 1, 33.33, 1, 1, 1, 34, 3);
INSERT INTO public."OrderItem" ("Id", "Quantity", "PricePerCraft", "Discount", "Status", "OrderId", "CraftId", "SellerId") VALUES (2, 2, 11.11, 1, 1, 2, 31, 2);
INSERT INTO public."OrderItem" ("Id", "Quantity", "PricePerCraft", "Discount", "Status", "OrderId", "CraftId", "SellerId") VALUES (3, 3, 60.33, 1, 1, 2, 27, 8);
INSERT INTO public."OrderItem" ("Id", "Quantity", "PricePerCraft", "Discount", "Status", "OrderId", "CraftId", "SellerId") VALUES (4, 2, 25.13, 1, 1, 3, 26, 8);
INSERT INTO public."OrderItem" ("Id", "Quantity", "PricePerCraft", "Discount", "Status", "OrderId", "CraftId", "SellerId") VALUES (5, 1, 68.84, 1, 1, 3, 29, 2);
INSERT INTO public."OrderItem" ("Id", "Quantity", "PricePerCraft", "Discount", "Status", "OrderId", "CraftId", "SellerId") VALUES (6, 1, 124, 1, 1, 4, 19, 1);
INSERT INTO public."OrderItem" ("Id", "Quantity", "PricePerCraft", "Discount", "Status", "OrderId", "CraftId", "SellerId") VALUES (7, 1, 43.23, 1, 1, 4, 15, 1);


--
-- Data for Name: Orders; Type: TABLE DATA; Schema: public; Owner: prime8bit
--

INSERT INTO public."Orders" ("Id", "OrderDate", "TotalPrice", "ShippingName", "ShippingAddress", "BillingName", "BillingAddress", "Status", "BuyerId") VALUES (1, '2026-07-06', 33.33, 'Roslyn Doyle', '29 Cardinal Drive Amarillo, TX 79106', 'Roslyn Doyle', '29 Cardinal Drive Amarillo, TX 79106', 1, 2);
INSERT INTO public."Orders" ("Id", "OrderDate", "TotalPrice", "ShippingName", "ShippingAddress", "BillingName", "BillingAddress", "Status", "BuyerId") VALUES (2, '2026-07-06', 71.44, 'Lisa Scott', '9834 Brook Lane Nottingham, MD 21236', 'Lisa Scott', '9834 Brook Lane Nottingham, MD 21236', 1, 1);
INSERT INTO public."Orders" ("Id", "OrderDate", "TotalPrice", "ShippingName", "ShippingAddress", "BillingName", "BillingAddress", "Status", "BuyerId") VALUES (3, '2026-07-06', 93.96999, 'Lisa Scott', '9834 Brook Lane Nottingham, MD 21236', 'Lisa Scott', '9834 Brook Lane Nottingham, MD 21236', 1, 1);
INSERT INTO public."Orders" ("Id", "OrderDate", "TotalPrice", "ShippingName", "ShippingAddress", "BillingName", "BillingAddress", "Status", "BuyerId") VALUES (4, '2026-07-06', 167.23, 'Niles Crane', '276 Cottage Street Monsey, NY 10952', 'Niles Crane', '276 Cottage Street Monsey, NY 10952', 1, 4);


--
-- Data for Name: UserMedia; Type: TABLE DATA; Schema: public; Owner: prime8bit
--

INSERT INTO public."UserMedia" ("Id", "UserId", "Url", "CloudId", "Type") VALUES (5, 5, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770531159/DefaultUser_q2oafb.jpg', 'DefaultUser_q2oafb', 1);
INSERT INTO public."UserMedia" ("Id", "UserId", "Url", "CloudId", "Type") VALUES (1, 1, 'https://res.cloudinary.com/db3ulheek/image/upload/v1774564615/Crafty/foso2gdcxpypfqsa3zm8.jpg', 'DefaultUser_q2oafb', 1);
INSERT INTO public."UserMedia" ("Id", "UserId", "Url", "CloudId", "Type") VALUES (2, 2, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770773499/Crafty/l3zyu4xux3l8q8pvanea.jpg', 'DefaultUser_q2oafb', 1);
INSERT INTO public."UserMedia" ("Id", "UserId", "Url", "CloudId", "Type") VALUES (3, 3, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770773650/Crafty/zmwoam4itdtztz6piwze.jpg', 'DefaultUser_q2oafb', 1);
INSERT INTO public."UserMedia" ("Id", "UserId", "Url", "CloudId", "Type") VALUES (4, 4, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770773858/Crafty/o1g4hlmflrvjb07gkzmg.jpg', 'DefaultUser_q2oafb', 1);
INSERT INTO public."UserMedia" ("Id", "UserId", "Url", "CloudId", "Type") VALUES (8, 8, 'https://res.cloudinary.com/db3ulheek/image/upload/v1770717362/Crafty/zdstq70vspq04kbptbsv.jpg', 'DefaultUser_q2oafb', 1);


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: prime8bit
--

INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20260706213826_PostgresInit', '9.0.14');


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: prime8bit
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- Name: AspNetRoles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: prime8bit
--

SELECT pg_catalog.setval('public."AspNetRoles_Id_seq"', 2, true);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: prime8bit
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- Name: AspNetUsers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: prime8bit
--

SELECT pg_catalog.setval('public."AspNetUsers_Id_seq"', 8, true);


--
-- Name: CraftMedia_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: prime8bit
--

SELECT pg_catalog.setval('public."CraftMedia_Id_seq"', 24, true);


--
-- Name: Crafts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: prime8bit
--

SELECT pg_catalog.setval('public."Crafts_Id_seq"', 14, true);


--
-- Name: Messages_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: prime8bit
--

SELECT pg_catalog.setval('public."Messages_Id_seq"', 8, true);


--
-- Name: OrderItem_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: prime8bit
--

SELECT pg_catalog.setval('public."OrderItem_Id_seq"', 7, true);


--
-- Name: Orders_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: prime8bit
--

SELECT pg_catalog.setval('public."Orders_Id_seq"', 4, true);


--
-- Name: UserMedia_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: prime8bit
--

SELECT pg_catalog.setval('public."UserMedia_Id_seq"', 8, true);


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: CraftMedia PK_CraftMedia; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."CraftMedia"
    ADD CONSTRAINT "PK_CraftMedia" PRIMARY KEY ("Id");


--
-- Name: CraftWishlistItems PK_CraftWishlistItems; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."CraftWishlistItems"
    ADD CONSTRAINT "PK_CraftWishlistItems" PRIMARY KEY ("WishlistedCraftId", "WishlistingUserId");


--
-- Name: Crafts PK_Crafts; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."Crafts"
    ADD CONSTRAINT "PK_Crafts" PRIMARY KEY ("Id");


--
-- Name: MessageConnections PK_MessageConnections; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."MessageConnections"
    ADD CONSTRAINT "PK_MessageConnections" PRIMARY KEY ("Id");


--
-- Name: MessageGroups PK_MessageGroups; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."MessageGroups"
    ADD CONSTRAINT "PK_MessageGroups" PRIMARY KEY ("Name");


--
-- Name: Messages PK_Messages; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT "PK_Messages" PRIMARY KEY ("Id");


--
-- Name: OrderItem PK_OrderItem; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."OrderItem"
    ADD CONSTRAINT "PK_OrderItem" PRIMARY KEY ("Id");


--
-- Name: Orders PK_Orders; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "PK_Orders" PRIMARY KEY ("Id");


--
-- Name: UserMedia PK_UserMedia; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."UserMedia"
    ADD CONSTRAINT "PK_UserMedia" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_CraftMedia_CraftId; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE INDEX "IX_CraftMedia_CraftId" ON public."CraftMedia" USING btree ("CraftId");


--
-- Name: IX_CraftWishlistItems_WishlistingUserId; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE INDEX "IX_CraftWishlistItems_WishlistingUserId" ON public."CraftWishlistItems" USING btree ("WishlistingUserId");


--
-- Name: IX_Crafts_SearchImageId; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE UNIQUE INDEX "IX_Crafts_SearchImageId" ON public."Crafts" USING btree ("SearchImageId");


--
-- Name: IX_Crafts_SellerId; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE INDEX "IX_Crafts_SellerId" ON public."Crafts" USING btree ("SellerId");


--
-- Name: IX_MessageConnections_MessageGroupName; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE INDEX "IX_MessageConnections_MessageGroupName" ON public."MessageConnections" USING btree ("MessageGroupName");


--
-- Name: IX_Messages_RecipientId; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE INDEX "IX_Messages_RecipientId" ON public."Messages" USING btree ("RecipientId");


--
-- Name: IX_Messages_SenderId; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE INDEX "IX_Messages_SenderId" ON public."Messages" USING btree ("SenderId");


--
-- Name: IX_OrderItem_CraftId; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE INDEX "IX_OrderItem_CraftId" ON public."OrderItem" USING btree ("CraftId");


--
-- Name: IX_OrderItem_OrderId; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE INDEX "IX_OrderItem_OrderId" ON public."OrderItem" USING btree ("OrderId");


--
-- Name: IX_OrderItem_SellerId; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE INDEX "IX_OrderItem_SellerId" ON public."OrderItem" USING btree ("SellerId");


--
-- Name: IX_Orders_BuyerId; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE INDEX "IX_Orders_BuyerId" ON public."Orders" USING btree ("BuyerId");


--
-- Name: IX_UserMedia_UserId; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE UNIQUE INDEX "IX_UserMedia_UserId" ON public."UserMedia" USING btree ("UserId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: prime8bit
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: CraftMedia FK_CraftMedia_Crafts_CraftId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."CraftMedia"
    ADD CONSTRAINT "FK_CraftMedia_Crafts_CraftId" FOREIGN KEY ("CraftId") REFERENCES public."Crafts"("Id") ON DELETE CASCADE;


--
-- Name: CraftWishlistItems FK_CraftWishlistItems_AspNetUsers_WishlistingUserId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."CraftWishlistItems"
    ADD CONSTRAINT "FK_CraftWishlistItems_AspNetUsers_WishlistingUserId" FOREIGN KEY ("WishlistingUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: CraftWishlistItems FK_CraftWishlistItems_Crafts_WishlistedCraftId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."CraftWishlistItems"
    ADD CONSTRAINT "FK_CraftWishlistItems_Crafts_WishlistedCraftId" FOREIGN KEY ("WishlistedCraftId") REFERENCES public."Crafts"("Id") ON DELETE CASCADE;


--
-- Name: Crafts FK_Crafts_AspNetUsers_SellerId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."Crafts"
    ADD CONSTRAINT "FK_Crafts_AspNetUsers_SellerId" FOREIGN KEY ("SellerId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Crafts FK_Crafts_CraftMedia_SearchImageId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."Crafts"
    ADD CONSTRAINT "FK_Crafts_CraftMedia_SearchImageId" FOREIGN KEY ("SearchImageId") REFERENCES public."CraftMedia"("Id") ON DELETE SET NULL;


--
-- Name: MessageConnections FK_MessageConnections_MessageGroups_MessageGroupName; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."MessageConnections"
    ADD CONSTRAINT "FK_MessageConnections_MessageGroups_MessageGroupName" FOREIGN KEY ("MessageGroupName") REFERENCES public."MessageGroups"("Name") ON DELETE CASCADE;


--
-- Name: Messages FK_Messages_AspNetUsers_RecipientId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT "FK_Messages_AspNetUsers_RecipientId" FOREIGN KEY ("RecipientId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Messages FK_Messages_AspNetUsers_SenderId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT "FK_Messages_AspNetUsers_SenderId" FOREIGN KEY ("SenderId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: OrderItem FK_OrderItem_AspNetUsers_SellerId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."OrderItem"
    ADD CONSTRAINT "FK_OrderItem_AspNetUsers_SellerId" FOREIGN KEY ("SellerId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: OrderItem FK_OrderItem_Crafts_CraftId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."OrderItem"
    ADD CONSTRAINT "FK_OrderItem_Crafts_CraftId" FOREIGN KEY ("CraftId") REFERENCES public."Crafts"("Id") ON DELETE CASCADE;


--
-- Name: OrderItem FK_OrderItem_Orders_OrderId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."OrderItem"
    ADD CONSTRAINT "FK_OrderItem_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id") ON DELETE CASCADE;


--
-- Name: Orders FK_Orders_AspNetUsers_BuyerId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "FK_Orders_AspNetUsers_BuyerId" FOREIGN KEY ("BuyerId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: UserMedia FK_UserMedia_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: prime8bit
--

ALTER TABLE ONLY public."UserMedia"
    ADD CONSTRAINT "FK_UserMedia_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


-- NATE: making sure to set the last autoincrement value to the max value for each table
DO $$
BEGIN
    PERFORM setval(
        pg_get_serial_sequence('public."CraftMedia"', 'Id'),
        (SELECT MAX("Id") FROM public."CraftMedia"),
        true
    );

    PERFORM setval(
        pg_get_serial_sequence('public."Crafts"', 'Id'),
        (SELECT MAX("Id") FROM public."Crafts"),
        true
    );

    PERFORM setval(
        pg_get_serial_sequence('public."Messages"', 'Id'),
        (SELECT MAX("Id") FROM public."Messages"),
        true
    );

    PERFORM setval(
        pg_get_serial_sequence('public."OrderItem"', 'Id'),
        (SELECT MAX("Id") FROM public."OrderItem"),
        true
    );

    PERFORM setval(
        pg_get_serial_sequence('public."Orders"', 'Id'),
        (SELECT MAX("Id") FROM public."Orders"),
        true
    );

    PERFORM setval(
        pg_get_serial_sequence('public."UserMedia"', 'Id'),
        (SELECT MAX("Id") FROM public."UserMedia"),
        true
    );
END $$;

--
-- PostgreSQL database dump complete
--

\unrestrict PPbQ4RYiIbXzHLk3tLDlfuGiwnQJz2KoKkNgIktD1ebbG6BSzDU7MsgGvHiZVT9

